name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Grant execute permission for gradlew
      working-directory: ./GithubAction
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./GithubAction/gradlew build
