name: Unit Test Action
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GithubAction
    steps:
      - name: Long-running task
        run: do-the-thing.sh
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: "/output"
          key: ${{ runner.os }}-$GITHUB_RUN_ID
          
  unit-tests:
      runs-on: ubuntu-latest
      steps:
      - name: use cache 
        uses: actions/cache@v2
        with:
          path: "/output"
          key: ${{ runner.os }}-$GITHUB_RUN_ID
      - name: run tests
        run: npm test:unit
