name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GithubAction
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
     
    - name: Make gradlew executable
      run: chmod +x ./gradlew
            
      # Execute coverage report - name: Unit Test
    - name: Unit Test coverage report
      run: ./gradlew createDebugUnitTestCoverageReport
 
    - name: Upload html coverage report
      uses: actions/upload-artifact@v3
      with:
          name: unit test coverage report upload
          path:  ./GithubAction/app/build/reports/coverage/test/debug/com.sava.githubaction
      
         
            # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
 
    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
          name: unit test result upload
          path:  ./GithubAction/app/build/reports/tests/testDebugUnitTest/index.html
          
          
      # Execute apk
    - name: Get apk path
      id: apk-path
      run: |
         path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
         echo "::set-output name=path::$path"
    
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug
      
    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
          name: App Debug APK
          path: ./GithubAction/app/build/outputs/
          
    - name: Generate Javadoc
      run: mvn org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:aggregate
      shell: bash
    - name: Deploy JavaDoc
      uses: avinal/github-pages-deploy-action@main
      with:
                    # GitHub access token with Repo Access
                    GITHUB_TOKEN: ${{ github.token }}
                    # For JavaDoc - "java"
                    # For python write python package and additional packages if any - "python3 python3-pip" 
                    LANGUAGE: "<write-as-directed-above>"
                    # Write make command to generate html e.g.- "make html"
                    MAKE_COMMAND: "make html"
                    # Write the branch name for storing github pages source 
                    PAGES_BRANCH: "main"
                    # Write the branch name having source files for site/documentation
                    BUILD_FROM: "main"
                    # Write the name of the output folder where generated html is stored by makefile.
                    DOCS_FOLDER: "GithubAction/app"

   # download all artifacts
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
