name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GithubAction
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
     
    - name: Make gradlew executable
      run: chmod +x ./gradlew
            
      # Execute coverage report - name: Unit Test
    - name: Unit Test coverage report
      run: ./gradlew createDebugUnitTestCoverageReport
 
    - name: Upload html coverage report
      uses: actions/upload-artifact@v3
      with:
          name: unit test coverage report upload
          path:  ./GithubAction/app/build/reports/coverage/test/debug/com.sava.githubaction
      
         
            # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
 
    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
          name: unit test result upload
          path:  ./GithubAction/app/build/reports/tests/testDebugUnitTest/index.html
          
          
      # Execute apk
    
    
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug
      
    - name: Get apk path
      id: apk-path
      run: |
         path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
         echo "::set-output name=path::$path"
         env:
          FOO= $path
         
    - name: other step that needs FOO
      run: echo ${{ env.FOO }}
    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
          name:  $(find **/build/outputs/apk -name '*.apk' -type f | head -1)
          path: ./GithubAction/app/build/outputs/
          
   
        
    - name: Get apk info
      id: apk-info
      uses: hkusu/apk-info-action@v1
      with:
            apk-path: ${{ steps.apk-path.outputs.path }}
            
    - name: Show apk info
      run: |
       echo '${{ steps.apk-info.outputs.application-name }}'
       echo '${{ steps.apk-info.outputs.application-id }}'
       echo '${{ steps.apk-info.outputs.version-code }}'
       echo '${{ steps.apk-info.outputs.version-name }}'
          

   # download all artifacts
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
