name: Build Project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GithubAction
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle
     
    - name: Make gradlew executable
      run: chmod +x ./gradlew
            
      # Execute coverage report - name: Unit Test
    - name: Unit Test coverage report
      run: ./gradlew createDebugUnitTestCoverageReport
 
    - name: Upload html coverage report
      uses: actions/upload-artifact@v3
      with:
          name: unit test coverage report upload
          path:  ./GithubAction/app/build/reports/coverage/test/debug/com.sava.githubaction
      
         
            # Execute unit tests
    - name: Unit Test
      run: ./gradlew testDebugUnitTest

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
 
    - name: Upload html test report
      uses: actions/upload-artifact@v3
      with:
          name: unit test result upload
          path:  ./GithubAction/app/build/reports/tests/testDebugUnitTest/index.html
          
          
      # Execute apk
    - name: Get apk path
      id: apk-path
      run: |
         path=$(find **/build/outputs/apk -name '*.apk' -type f | head -1)
         echo "::set-output name=path::$path"
    
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug
      
    - name: Upload apk
      uses: actions/upload-artifact@v3
      with:
          name: App Debug APK
          path: ./GithubAction/app/build/outputs/
          
    - name: Get version
      run: |
             echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
         
          
    - name: Deploy JavaDoc 🚀
      uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.4
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: main
          java-version: 17
          target-folder: javadoc 

   # download all artifacts
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
